# -*- coding: utf-8 -*-
"""GradientBoosttask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136jBz5OAR1f49Zt6bMEOLa5ZQsRW4h4K
"""

import pandas as pd
df=pd.read_csv("/content/mushroom_classification.csv")
print(df.shape)
df.head()



g=df.groupby("class")[
    ["cap_diameter", "stem_height", "stem_width"]
].mean()
print(g)
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
sns.boxplot(x="class", y="cap_diameter", data=df)
plt.title("Cap Diameter")
plt.subplot(1, 3, 2)
sns.boxplot(x="class", y="stem_height", data=df)
plt.title("Stem Height")
plt.subplot(1, 3, 3)
sns.boxplot(x="class", y="stem_width", data=df)
plt.title("Stem Width")
plt.tight_layout()
plt.show()

x=df[['cap_diameter', 'cap_shape', 'gill_attachment', 'gill_color', 'stem_height', 'stem_width', 'stem_color', 'season']]
y=df['class']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
from sklearn.linear_model import LogisticRegression
l_model=LogisticRegression()
l_model.fit(x_train,y_train)
l_pred=l_model.predict(x_test)
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,l_pred))
print(classification_report(y_test,l_pred))

from sklearn.tree import DecisionTreeClassifier
d_model=DecisionTreeClassifier()
d_model.fit(x_train,y_train)
d_pred=d_model.predict(x_test)
print(accuracy_score(y_test,d_pred))
print(classification_report(y_test,d_pred))

importances = d_model.feature_importances_
feature_importance_df = pd.DataFrame({
    "Feature": x.columns,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)
print(feature_importance_df)

from sklearn.ensemble import GradientBoostingClassifier
gb_model = GradientBoostingClassifier(
    learning_rate=0.05,
    n_estimators=150,
    max_depth=4,
    min_samples_split=3,
    min_samples_leaf=2,
    random_state=42
)
gb_model.fit(x_train, y_train)

gb_pred = gb_model.predict(x_test)
print(accuracy_score(y_test, gb_pred))

import joblib
joblib.dump(d_model,"deci.pkl")